In [ ]:
print("Hello Adon")

Hello Adon

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving movies.csv to movies.csv

In [ ]:
import pandas as pd

movies = pd.read_csv('movies.csv')

movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [ ]:
movies.shape

(9742, 3)

In [ ]:
movies['genres'].unique()[:10]

array(['Adventure|Animation|Children|Comedy|Fantasy',
       'Adventure|Children|Fantasy', 'Comedy|Romance',
       'Comedy|Drama|Romance', 'Comedy', 'Action|Crime|Thriller',
       'Adventure|Children', 'Action', 'Action|Adventure|Thriller',
       'Comedy|Horror'], dtype=object)

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving ratings.csv to ratings.csv

In [ ]:
ratings = pd.read_csv('ratings.csv')

ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [ ]:
movies.shape

(9742, 3)

In [ ]:
movies['genres'].unique()[:10]

array(['Adventure|Animation|Children|Comedy|Fantasy',
       'Adventure|Children|Fantasy', 'Comedy|Romance',
       'Comedy|Drama|Romance', 'Comedy', 'Action|Crime|Thriller',
       'Adventure|Children', 'Action', 'Action|Adventure|Thriller',
       'Comedy|Horror'], dtype=object)

In [ ]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [ ]:
movie_ratings = ratings.groupby('movieId')['rating'].mean()

movie_ratings.head()

movieId
1    3.920930
2    3.431818
3    3.259615
4    2.357143
5    3.071429
Name: rating, dtype: float64

In [ ]:
movie_ratings = movie_ratings.reset_index()

movies_df = movies.merge(
    movie_ratings,
    on='movieId'
)

movies_df.head()

,movieId,title,genres,rating
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.920930
1,2,Jumanji (1995),Adventure|Children|Fantasy,3.431818
2,3,Grumpier Old Men (1995),Comedy|Romance,3.259615
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.357143
4,5,Father of the Bride Part II (1995),Comedy,3.071429

In [ ]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9724 entries, 0 to 9723
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9724 non-null   int64
 1   title    9724 non-null   object
 2   genres   9724 non-null   object
 3   rating   9724 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 304.0+ KB

In [ ]:
movies_df.head()

,movieId,title,genres,rating
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.920930
1,2,Jumanji (1995),Adventure|Children|Fantasy,3.431818
2,3,Grumpier Old Men (1995),Comedy|Romance,3.259615
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.357143
4,5,Father of the Bride Part II (1995),Comedy,3.071429

In [ ]:
def recommend_by_genre(genre):

    results = movies_df[
        movies_df['genres'].str.contains(
            genre,
            case=False,
            na=False
        )
    ]

    return results[
        ['title','genres','rating']
    ].sort_values(
        by='rating',
        ascending=False
    ).head(10)

In [ ]:
recommend_by_genre("Comedy")

,title,genres,rating
2336,My Man Godfrey (1957),Comedy,5.0
7383,Get Low (2009),Comedy|Drama|Mystery,5.0
7157,Love Exposure (Ai No Mukidashi) (2008),Action|Comedy|Drama|Romance,5.0
7117,Tyler Perry's I Can Do Bad All by Myself (2009),Comedy|Drama,5.0
7030,Boy Eats Girl (2005),Comedy|Horror,5.0
2661,Bossa Nova (2000),Comedy|Drama|Romance,5.0
2635,All the Vermeers in New York (1990),Comedy|Drama|Romance,5.0
9405,Alesha Popovich and Tugarin the Dragon (2004),Animation|Comedy|Drama,5.0
9570,Bobik Visiting Barbos (1977),Animation|Comedy,5.0
9557,Obsession (1965),Comedy,5.0

In [ ]:
movie_ratings = ratings.groupby('movieId')['rating'].mean()

In [ ]:
movie_ratings = movie_ratings.reset_index()

movies_df = movies.merge(
    movie_ratings,
    on='movieId'
)

In [ ]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9724 entries, 0 to 9723
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9724 non-null   int64
 1   title    9724 non-null   object
 2   genres   9724 non-null   object
 3   rating   9724 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 304.0+ KB

In [ ]:
recommend_by_genre("Comedy")

,title,genres,rating
2336,My Man Godfrey (1957),Comedy,5.0
7383,Get Low (2009),Comedy|Drama|Mystery,5.0
7157,Love Exposure (Ai No Mukidashi) (2008),Action|Comedy|Drama|Romance,5.0
7117,Tyler Perry's I Can Do Bad All by Myself (2009),Comedy|Drama,5.0
7030,Boy Eats Girl (2005),Comedy|Horror,5.0
2661,Bossa Nova (2000),Comedy|Drama|Romance,5.0
2635,All the Vermeers in New York (1990),Comedy|Drama|Romance,5.0
9405,Alesha Popovich and Tugarin the Dragon (2004),Animation|Comedy|Drama,5.0
9570,Bobik Visiting Barbos (1977),Animation|Comedy,5.0
9557,Obsession (1965),Comedy,5.0

In [ ]:
movie_ratings = ratings.groupby('movieId')['rating'].mean()

movie_ratings = movie_ratings.reset_index()

movies_df = movies.merge(movie_ratings, on='movieId')

movies_df.head()

,movieId,title,genres,rating
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.920930
1,2,Jumanji (1995),Adventure|Children|Fantasy,3.431818
2,3,Grumpier Old Men (1995),Comedy|Romance,3.259615
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.357143
4,5,Father of the Bride Part II (1995),Comedy,3.071429

In [ ]:
def recommend_by_genre(genre):

    results = movies_df[
        movies_df['genres'].str.contains(
            genre,
            case=False,
            na=False
        )
    ]

    results = results.sort_values(
        by='rating',
        ascending=False
    )

    return results[
        ['title', 'genres', 'rating']
    ].head(10)

In [ ]:
recommend_by_genre("Comedy")

,title,genres,rating
2336,My Man Godfrey (1957),Comedy,5.0
7383,Get Low (2009),Comedy|Drama|Mystery,5.0
7157,Love Exposure (Ai No Mukidashi) (2008),Action|Comedy|Drama|Romance,5.0
7117,Tyler Perry's I Can Do Bad All by Myself (2009),Comedy|Drama,5.0
7030,Boy Eats Girl (2005),Comedy|Horror,5.0
2661,Bossa Nova (2000),Comedy|Drama|Romance,5.0
2635,All the Vermeers in New York (1990),Comedy|Drama|Romance,5.0
9405,Alesha Popovich and Tugarin the Dragon (2004),Animation|Comedy|Drama,5.0
9570,Bobik Visiting Barbos (1977),Animation|Comedy,5.0
9557,Obsession (1965),Comedy,5.0

In [ ]:
recommend_by_genre("Action")

,title,genres,rating
8130,Justice League: Doom (2012),Action|Animation|Fantasy,5.0
5572,Sonatine (Sonachine) (1993),Action|Comedy|Crime|Drama,5.0
5490,Last Hurrah for Chivalry (Hao xia) (1979),Action|Drama,5.0
8097,Maniac Cop 2 (1990),Action|Horror|Thriller,5.0
5453,Branded to Kill (Koroshi no rakuin) (1967),Action|Crime|Drama,5.0
8348,On the Other Side of the Tracks (De l'autre cô...,Action|Comedy|Crime,5.0
8337,Wonder Woman (2009),Action|Adventure|Animation|Fantasy,5.0
8533,Crippled Avengers (Can que) (Return of the 5 D...,Action|Adventure,5.0
1227,"Assignment, The (1997)",Action|Thriller,5.0
7885,Superman/Batman: Public Enemies (2009),Action|Animation|Fantasy,5.0

In [ ]:
recommend_by_genre("Drama")

,title,genres,rating
5277,"Woman Is a Woman, A (femme est une femme, Une)...",Comedy|Drama|Musical|Romance,5.0
6903,Che: Part Two (2008),Drama|War,5.0
4468,Umberto D. (1952),Drama,5.0
869,Lesson Faust (1994),Animation|Comedy|Drama|Fantasy,5.0
2607,Madame Sousatzka (1988),Drama,5.0
6982,Strictly Sexual (2008),Comedy|Drama|Romance,5.0
2635,All the Vermeers in New York (1990),Comedy|Drama|Romance,5.0
864,Entertaining Angels: The Dorothy Day Story (1996),Drama,5.0
5665,Battle Royale 2: Requiem (Batoru rowaiaru II: ...,Action|Drama|Thriller|War,5.0
4667,Jane Eyre (1944),Drama|Romance,5.0

In [ ]:
def recommend_movies(genre, min_rating=4.0):

    results = movies_df[
        (movies_df['genres'].str.contains(
            genre,
            case=False,
            na=False
        ))
        &
        (movies_df['rating'] >= min_rating)
    ]

    results = results.sort_values(
        by='rating',
        ascending=False
    )

    return results[
        ['title','genres','rating']
    ].head(10)

In [ ]:
recommend_movies("Comedy", 4.5)

,title,genres,rating
9570,Bobik Visiting Barbos (1977),Animation|Comedy,5.0
405,Live Nude Girls (1995),Comedy,5.0
433,What Happened Was... (1994),Comedy|Drama|Romance|Thriller,5.0
531,"Thin Line Between Love and Hate, A (1996)",Comedy,5.0
536,Denise Calls Up (1995),Comedy,5.0
9347,Tom Segura: Mostly Stories (2016),Comedy,5.0
9281,All Yours (2016),Comedy|Drama|Romance,5.0
9271,World of Glory (1991),Comedy,5.0
9263,Tenchi Muyô! In Love (1996),Animation|Comedy,5.0
9237,Ice Age: The Great Egg-Scapade (2016),Adventure|Animation|Children|Comedy,5.0

In [ ]:
recommend_movies("Action", 4.0)

,title,genres,rating
666,Supercop 2 (Project S) (Chao ji ji hua) (1993),Action|Comedy|Crime|Thriller,5.0
1227,"Assignment, The (1997)",Action|Thriller,5.0
1646,Knock Off (1998),Action,5.0
3106,Reform School Girls (1986),Action|Drama,5.0
4039,Galaxy of Terror (Quest) (1981),Action|Horror|Mystery|Sci-Fi,5.0
3903,The Big Bus (1976),Action|Comedy,5.0
3754,Shogun Assassin (1980),Action|Adventure,5.0
5572,Sonatine (Sonachine) (1993),Action|Comedy|Crime|Drama,5.0
5665,Battle Royale 2: Requiem (Batoru rowaiaru II: ...,Action|Drama|Thriller|War,5.0
5490,Last Hurrah for Chivalry (Hao xia) (1979),Action|Drama,5.0

In [ ]:
#release year filtering

In [ ]:
movies_df['year'] = movies_df['title'].str.extract(r'\((\d{4})\)')

In [ ]:
movies_df[['title','year']].head()

                                title  year
0                    Toy Story (1995)  1995
1                      Jumanji (1995)  1995
2             Grumpier Old Men (1995)  1995
3            Waiting to Exhale (1995)  1995
4  Father of the Bride Part II (1995)  1995

In [ ]:
movies_df['year'] = pd.to_numeric(
    movies_df['year'],
    errors='coerce'
)